/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codingchallenge;

import javax.swing.JOptionPane;

/**
 *
 * @author Alvin Ray Dinlasan
 */
public class LoadScrn extends javax.swing.JFrame {

    /**
     * Creates new form LoadScrn
     */
    public LoadScrn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgcolor = new javax.swing.JPanel();
        loadbar = new javax.swing.JProgressBar();
        loadlabel = new javax.swing.JLabel();
        loadval = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();
        bgimg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bgcolor.setBackground(new java.awt.Color(255, 102, 51));
        bgcolor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bgcolor.add(loadbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 900, 10));

        loadlabel.setForeground(new java.awt.Color(255, 255, 255));
        loadlabel.setText("Loading...");
        bgcolor.add(loadlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        loadval.setText("0 %");
        bgcolor.add(loadval, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 40, -1));

        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/chocolate.gif"))); // NOI18N
        bgcolor.add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 500));

        bgimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/Wiki-background.jpg"))); // NOI18N
        bgcolor.add(bgimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgcolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgcolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        LoadScrn sp = new LoadScrn();
        sp.setVisible(true);
        
        try {
            
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                sp.loadval.setText(i + "%");
                
                if(i==10){
                    sp.loadlabel.setText("Connecting to network...");
                }
                if(i==20){
                    sp.loadlabel.setText("Checking machine inventory...");
                }
                if(i==50){
                    sp.loadlabel.setText("Machine replenishing...");
                }
                if(i==80){
                    sp.loadlabel.setText("Launching application...");
                }
                if(i==100){
                    VendingMachine vend = new VendingMachine();
                    vend.show();
                    sp.setVisible(false);
                }
                sp.loadbar.setValue(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgcolor;
    private javax.swing.JLabel bgimg;
    private javax.swing.JLabel bgimg2;
    private javax.swing.JProgressBar loadbar;
    private javax.swing.JLabel loadlabel;
    private javax.swing.JLabel loadval;
    // End of variables declaration//GEN-END:variables
}
