/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codingchallenge;

import static codingchallenge.VendingMachine.amountval;
import static codingchallenge.VendingMachine.cashval;
import static codingchallenge.VendingMachine.changeval;
import static codingchallenge.VendingMachine.itemcodeval;
import static codingchallenge.VendingMachine.itemnameval;
import static codingchallenge.VendingMachine.priceval;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.DateFormat;

/**
 *
 * @author Alvin Ray Dinlasan
 */
public class Receipt extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
        
        Date rcpt = new Date();
                
        SimpleDateFormat sdf = new SimpleDateFormat("dd-mm-yyyy hh:mm a");
        
        String strdate = sdf.format(rcpt);
        dateval.setText(strdate);
        String itmcode = VendingMachine.itemcodeval.getText();
        String itmname = VendingMachine.itemnameval.getText();
        String prc = VendingMachine.priceval.getText();
        String csh = VendingMachine.cashval.getText();
        String chng = VendingMachine.changeval.getText();
        
        itemcodeval1.setText(itmcode);
        itemnameval1.setText(itmname);
        priceval1.setText(prc);
        cashval1.setText(csh);
        changeval1.setText(chng);
    
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Receipttitle = new javax.swing.JLabel();
        itemcodelabel = new javax.swing.JLabel();
        itemcodeval1 = new javax.swing.JLabel();
        itemnamelabel = new javax.swing.JLabel();
        itemnameval1 = new javax.swing.JLabel();
        pricelabel = new javax.swing.JLabel();
        priceval1 = new javax.swing.JLabel();
        cashlabel = new javax.swing.JLabel();
        cashval1 = new javax.swing.JLabel();
        changeval1 = new javax.swing.JLabel();
        changelabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        dateval = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rcptbgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Receipttitle.setFont(new java.awt.Font("Niagara Engraved", 0, 75)); // NOI18N
        Receipttitle.setForeground(new java.awt.Color(255, 255, 255));
        Receipttitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receipttitle.setText("Thank You");
        Receipttitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Receipttitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 320, 90));

        itemcodelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemcodelabel.setForeground(new java.awt.Color(255, 255, 255));
        itemcodelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcodelabel.setText("Item Code:");
        itemcodelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(itemcodelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 30));

        itemcodeval1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemcodeval1.setForeground(new java.awt.Color(255, 255, 255));
        itemcodeval1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcodeval1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(itemcodeval1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 220, 30));

        itemnamelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        itemnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemnamelabel.setText("Item Name:");
        itemnamelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(itemnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, 30));

        itemnameval1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemnameval1.setForeground(new java.awt.Color(255, 255, 255));
        itemnameval1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemnameval1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(itemnameval1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 220, 30));

        pricelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pricelabel.setForeground(new java.awt.Color(255, 255, 255));
        pricelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pricelabel.setText("Price:");
        pricelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(pricelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 80, 30));

        priceval1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceval1.setForeground(new java.awt.Color(255, 255, 255));
        priceval1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceval1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(priceval1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 220, 30));

        cashlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashlabel.setForeground(new java.awt.Color(255, 255, 255));
        cashlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashlabel.setText("Cash");
        cashlabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(cashlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 80, 30));

        cashval1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashval1.setForeground(new java.awt.Color(255, 255, 255));
        cashval1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashval1.setText("$ 0.00");
        cashval1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(cashval1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 220, 30));

        changeval1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeval1.setForeground(new java.awt.Color(255, 255, 255));
        changeval1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeval1.setText("$ 0.00");
        changeval1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(changeval1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 220, 30));

        changelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changelabel.setForeground(new java.awt.Color(255, 255, 255));
        changelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changelabel.setText("Change");
        changelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(changelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 80, 30));

        datelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datelabel.setForeground(new java.awt.Color(255, 255, 255));
        datelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datelabel.setText("Date:");
        datelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(datelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 30));

        dateval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateval.setForeground(new java.awt.Color(255, 255, 255));
        dateval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateval.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(dateval, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 220, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 180, 60));

        rcptbgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/Wiki-background.jpg"))); // NOI18N
        jPanel1.add(rcptbgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, -10, 770, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        itemcodeval.setText("");
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        cashval.setText("");
        changeval.setText("");
        VendingMachine.buttoncheckout.setVisible(false);
        VendingMachine.cashlabel.setVisible(false);
        cashval.setVisible(false);
        VendingMachine.changelabel.setVisible(false);
        changeval.setVisible(false);
        
     dispose();
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Receipttitle;
    private javax.swing.JLabel cashlabel;
    private javax.swing.JLabel cashval1;
    private javax.swing.JLabel changelabel;
    private javax.swing.JLabel changeval1;
    private javax.swing.JLabel datelabel;
    public static javax.swing.JLabel dateval;
    private javax.swing.JLabel itemcodelabel;
    private javax.swing.JLabel itemcodeval1;
    private javax.swing.JLabel itemnamelabel;
    private javax.swing.JLabel itemnameval1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JLabel priceval1;
    private javax.swing.JLabel rcptbgimg;
    // End of variables declaration//GEN-END:variables
}
