/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codingchallenge;

import java.util.Date;
import javax.management.modelmbean.ModelMBean;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



        
/**
 *
 * @author Alvin Ray Dinlasan
 */
public class ServiceOption extends javax.swing.JFrame {

        
    /**
     * Creates new form ServiceOption
     */
    
   
    
    public ServiceOption() {
        initComponents();
       
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        itemcodelabel1 = new javax.swing.JLabel();
        itemnamelabel1 = new javax.swing.JLabel();
        amountlabel1 = new javax.swing.JLabel();
        pricelabel1 = new javax.swing.JLabel();
        itemcodeentry = new javax.swing.JTextField();
        itemnameentry = new javax.swing.JTextField();
        amountentry = new javax.swing.JTextField();
        priceentry = new javax.swing.JTextField();
        addentry = new javax.swing.JButton();
        deleteentry = new javax.swing.JButton();
        updateentry = new javax.swing.JButton();
        clearentry = new javax.swing.JButton();
        itemcodelabel2 = new javax.swing.JLabel();
        Servicetitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblitem = new javax.swing.JTable();
        servicebgimg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemcodelabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemcodelabel1.setForeground(new java.awt.Color(255, 255, 255));
        itemcodelabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcodelabel1.setText("Item Code:");
        itemcodelabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(itemcodelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 80, 30));

        itemnamelabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemnamelabel1.setForeground(new java.awt.Color(255, 255, 255));
        itemnamelabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemnamelabel1.setText("Item Name:");
        itemnamelabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(itemnamelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 80, 30));

        amountlabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountlabel1.setForeground(new java.awt.Color(255, 255, 255));
        amountlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountlabel1.setText("Amount:");
        amountlabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(amountlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 80, 30));

        pricelabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pricelabel1.setForeground(new java.awt.Color(255, 255, 255));
        pricelabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pricelabel1.setText("Price:");
        pricelabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(pricelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 80, 30));

        itemcodeentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcodeentryActionPerformed(evt);
            }
        });
        jPanel1.add(itemcodeentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 290, 30));

        itemnameentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnameentryActionPerformed(evt);
            }
        });
        jPanel1.add(itemnameentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 290, 30));

        amountentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountentryActionPerformed(evt);
            }
        });
        jPanel1.add(amountentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 290, 30));

        priceentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceentryActionPerformed(evt);
            }
        });
        jPanel1.add(priceentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 290, 30));

        addentry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addentry.setText("Add");
        addentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addentryActionPerformed(evt);
            }
        });
        jPanel1.add(addentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 120, 70));

        deleteentry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteentry.setText("Delete");
        deleteentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteentryActionPerformed(evt);
            }
        });
        jPanel1.add(deleteentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 120, 70));

        updateentry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateentry.setText("Update");
        updateentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateentryActionPerformed(evt);
            }
        });
        jPanel1.add(updateentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 120, 70));

        clearentry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clearentry.setText("Clear");
        clearentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearentryActionPerformed(evt);
            }
        });
        jPanel1.add(clearentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 120, 70));

        itemcodelabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemcodelabel2.setForeground(new java.awt.Color(255, 255, 255));
        itemcodelabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcodelabel2.setText("Close");
        itemcodelabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        itemcodelabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemcodelabel2MouseClicked(evt);
            }
        });
        jPanel1.add(itemcodelabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        Servicetitle.setFont(new java.awt.Font("Niagara Engraved", 0, 75)); // NOI18N
        Servicetitle.setForeground(new java.awt.Color(255, 255, 255));
        Servicetitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Servicetitle.setText("Machine Service Options");
        Servicetitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Servicetitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, 120));

        tblitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A1", "Snickers", "10", "1.35"},
                {"A2", "Snickers", "10", "1.35"},
                {"A3", "Snickers", "10", "1.35"},
                {"A4", "Snickers", "10", "1.35"},
                {"A5", "Hershey's", "10", "2.25"},
                {"A6", "Hershey's", "10", "2.25"},
                {"A7", "Hershey's", "10", "2.25"},
                {"A8", "Hershey's", "10", "2.25"},
                {"B1", "Reese's", "10", "1.05"},
                {"B2", "Reese's", "10", "1.05"},
                {"B3", "Reese's", "10", "1.05"},
                {"B4", "Reese's", "10", "1.05"},
                {"B5", "Hershey's Almond", "10", "1.80"},
                {"B6", "Hershey's Almond", "10", "1.80"},
                {"B7", "Hershey's Special Dark", "10", "1.75"},
                {"B8", "Hershey's Special Dark", "10", "1.75"},
                {"C1", "Nutrageous", "10", "1.30"},
                {"C2", "Nutrageous", "10", "1.30"},
                {"C3", "Nutrageous", "10", "1.30"},
                {"C4", "Nutrageous", "10", "1.30"},
                {"C5", "Baby Ruth", "10", "2.50"},
                {"C6", "Baby Ruth", "10", "2.50"},
                {"C7", "Baby Ruth", "10", "2.50"},
                {"C8", "Baby Ruth", "10", "2.50"},
                {"D1", "MilkyWay", "10", "1.00"},
                {"D2", "MilkyWay", "10", "1.00"},
                {"D3", "MilkyWay", "10", "1.00"},
                {"D4", "MilkyWay", "10", "1.00"},
                {"D5", "M&M's", "10", "1.25"},
                {"D6", "M&M's", "10", "1.25"},
                {"D7", "M&M's", "10", "1.25"},
                {"D8", "M&M's", "10", null}
            },
            new String [] {
                "ItemCode", "ItemName", "Amount", "Price"
            }
        ));
        tblitem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblitemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblitem);
        tblitem.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, 610));

        servicebgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/Wiki-background.jpg"))); // NOI18N
        jPanel1.add(servicebgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -110, 1390, 770));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void amountentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountentryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountentryActionPerformed

    private void priceentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceentryActionPerformed
        
    }//GEN-LAST:event_priceentryActionPerformed

    private void itemnameentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnameentryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemnameentryActionPerformed

    private void itemcodeentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcodeentryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemcodeentryActionPerformed

    private void addentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addentryActionPerformed
       DefaultTableModel tblmodel = (DefaultTableModel)tblitem.getModel();
        tblmodel.addRow(new Object[]{itemcodeentry.getText(), itemnameentry.getText(), amountentry.getText(), priceentry.getText()});
        JOptionPane.showMessageDialog(this, "New Item Uploaded!");
        
        Date obj = new Date();
        
        System.out.println(obj);
        System.out.println("New Item Uploaded:");
        System.out.println("Item Code:  " + itemcodeentry.getText());
        System.out.println("Item Name:  " + itemnameentry.getText());
        System.out.println("Amount:  " + amountentry.getText());
        System.out.println("Price:  " + priceentry.getText());
        System.out.println("============================================");
        
        tblitem.clearSelection();
        itemcodeentry.setText("");
        itemnameentry.setText("");
        amountentry.setText("");
        priceentry.setText("");
    }//GEN-LAST:event_addentryActionPerformed

    private void tblitemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblitemMouseClicked
       DefaultTableModel tblmodel = (DefaultTableModel)tblitem.getModel();
       String tblitemcode = tblmodel.getValueAt(tblitem.getSelectedRow(),0).toString();
       String tblitemname = tblmodel.getValueAt(tblitem.getSelectedRow(),1).toString();
       String tblamount = tblmodel.getValueAt(tblitem.getSelectedRow(),2).toString();
       String tblprice = tblmodel.getValueAt(tblitem.getSelectedRow(),3).toString();
        
       itemcodeentry.setText(tblitemcode);
       itemnameentry.setText(tblitemname);
       amountentry.setText(tblamount);
       priceentry.setText(tblprice);
       
          
    }//GEN-LAST:event_tblitemMouseClicked

    private void updateentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateentryActionPerformed
       
       DefaultTableModel tblmodel = (DefaultTableModel)tblitem.getModel();
       if(tblitem.getSelectedRowCount()==1){
           
        String itemcode = itemcodeentry.getText();
        String itemname = itemnameentry.getText();
        String amount = amountentry.getText();
        String price = priceentry.getText();
       
       
        tblmodel.setValueAt(itemcode, tblitem.getSelectedRow(),0);
        tblmodel.setValueAt(itemname, tblitem.getSelectedRow(),1);
        tblmodel.setValueAt(amount, tblitem.getSelectedRow(),2);
        tblmodel.setValueAt(price, tblitem.getSelectedRow(),3);
        
           JOptionPane.showMessageDialog(this, "Update Successful!");
           
        Date obj = new Date();
        
        System.out.println(obj);
        System.out.println("Item Updated:");
        System.out.println("Item Code:  " + itemcodeentry.getText());
        System.out.println("Item Name:  " + itemnameentry.getText());
        System.out.println("Amount:  " + amountentry.getText());
        System.out.println("Price:  " + priceentry.getText());
        System.out.println("============================================");
        
        tblitem.clearSelection();
        itemcodeentry.setText("");
        itemnameentry.setText("");
        amountentry.setText("");
        priceentry.setText("");
              
       }
       
       else{
           if(itemcodeentry.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Forms are Empty!");
           }
       }
       
       
    }//GEN-LAST:event_updateentryActionPerformed

    private void clearentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearentryActionPerformed
        tblitem.clearSelection();
        itemcodeentry.setText("");
        itemnameentry.setText("");
        amountentry.setText("");
        priceentry.setText("");
    }//GEN-LAST:event_clearentryActionPerformed

    private void deleteentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteentryActionPerformed
       DefaultTableModel tblmodel = (DefaultTableModel)tblitem.getModel();
       if(tblitem.getSelectedRowCount()==1){
          int response = JOptionPane.showConfirmDialog(this,"Do you want to continueaction?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
           
          if(response == JOptionPane.YES_OPTION){
              tblmodel.removeRow(tblitem.getSelectedRow());
              
              Date obj = new Date();
        
                System.out.println(obj);
                System.out.println("Item Deleted:");
                System.out.println("Item Code:  " + itemcodeentry.getText());
                System.out.println("Item Name:  " + itemnameentry.getText());
                System.out.println("Amount:  " + amountentry.getText());
                System.out.println("Price:  " + priceentry.getText());
                System.out.println("============================================");
              
              tblitem.clearSelection();
              itemcodeentry.setText("");
              itemnameentry.setText("");
              amountentry.setText("");
              priceentry.setText("");
          }
          else{
          }
                     
       }
    }//GEN-LAST:event_deleteentryActionPerformed

    private void itemcodelabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemcodelabel2MouseClicked
        
        VendingMachine.samount = 10;
        VendingMachine.hamount = 10;
        VendingMachine.haamount = 10;
        VendingMachine.hsdamount = 10;
        VendingMachine.ramount = 10;
        VendingMachine.nramount = 10;
        VendingMachine.bramount = 10;
        VendingMachine.mwamount = 10;
        VendingMachine.mmamount = 10;
        
        
        VendingMachine vend = new VendingMachine();
        vend.show();
        
        dispose();
        
    }//GEN-LAST:event_itemcodelabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Servicetitle;
    private javax.swing.JButton addentry;
    private javax.swing.JTextField amountentry;
    private javax.swing.JLabel amountlabel1;
    private javax.swing.JButton clearentry;
    private javax.swing.JButton deleteentry;
    private javax.swing.JTextField itemcodeentry;
    private javax.swing.JLabel itemcodelabel1;
    private javax.swing.JLabel itemcodelabel2;
    private javax.swing.JTextField itemnameentry;
    private javax.swing.JLabel itemnamelabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceentry;
    private javax.swing.JLabel pricelabel1;
    private javax.swing.JLabel servicebgimg;
    private javax.swing.JTable tblitem;
    private javax.swing.JButton updateentry;
    // End of variables declaration//GEN-END:variables
}
