/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codingchallenge;

import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alvin Ray Dinlasan
 */
public class VendingMachine extends javax.swing.JFrame {

    /**
     * Creates new form VendingMachine
     */
    
    /* amount values*/
    public static int samount = 10;
    public static int hamount = 10;
    public static int ramount = 10;
    public static int haamount = 10;
    public static int hsdamount = 10;
    public static int nramount = 10;
    public static int bramount = 10;
    public static int mwamount = 10;
    public static int mmamount = 10;
    public static int remain;    
    
    /* price values*/    
   public static double sprice = 1.35;
   public static double hprice = 2.25;
   public static double haprice = 1.80;
   public static double hsdprice = 1.75;
   public static double rprice = 1.05;
   public static double nrprice = 1.30;
   public static double brprice = 2.50;
   public static double mwprice = 1.00;
   public static double mmprice = 1.25;
   
   public static double payments;
   public static double change;
   public static double balance;
            
    public VendingMachine() {
        initComponents();
        
        buttoncheckout.setVisible(false);
        cashlabel.setVisible(false);
        cashval.setVisible(false);
        changelabel.setVisible(false);
        changeval.setVisible(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void Entervalue(String q){
    String value = itemcodeval.getText() + q;
    itemcodeval.setText(value);
          
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vendpanel = new javax.swing.JPanel();
        vendbg = new javax.swing.JPanel();
        Brow = new javax.swing.JLabel();
        Arow = new javax.swing.JLabel();
        Crow = new javax.swing.JLabel();
        Drow = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        col1 = new javax.swing.JLabel();
        col2 = new javax.swing.JLabel();
        col3 = new javax.swing.JLabel();
        col4 = new javax.swing.JLabel();
        col5 = new javax.swing.JLabel();
        col6 = new javax.swing.JLabel();
        col7 = new javax.swing.JLabel();
        col8 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        B8 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        C7 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        D8 = new javax.swing.JLabel();
        buttonA = new javax.swing.JButton();
        buttonB = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonD = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonepay = new javax.swing.JButton();
        buttonclear = new javax.swing.JButton();
        buttoncheckout = new javax.swing.JButton();
        itemcodelabel = new javax.swing.JLabel();
        amountlabel = new javax.swing.JLabel();
        pricelabel = new javax.swing.JLabel();
        priceval = new javax.swing.JLabel();
        amountval = new javax.swing.JLabel();
        itemcodeval = new javax.swing.JLabel();
        itemnamelabel = new javax.swing.JLabel();
        itemnameval = new javax.swing.JLabel();
        cashlabel = new javax.swing.JLabel();
        cashval = new javax.swing.JLabel();
        changeval = new javax.swing.JLabel();
        changelabel = new javax.swing.JLabel();
        vendbgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1080, 720));

        vendpanel.setBackground(new java.awt.Color(255, 153, 0));
        vendpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vendbg.setBackground(new java.awt.Color(255, 255, 255));
        vendbg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendbg.setOpaque(false);

        Brow.setBackground(new java.awt.Color(255, 255, 255));
        Brow.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Brow.setForeground(new java.awt.Color(255, 255, 255));
        Brow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Brow.setText("B");
        Brow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Arow.setBackground(new java.awt.Color(255, 255, 255));
        Arow.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Arow.setForeground(new java.awt.Color(255, 255, 255));
        Arow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Arow.setText("A");
        Arow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Crow.setBackground(new java.awt.Color(255, 255, 255));
        Crow.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Crow.setForeground(new java.awt.Color(255, 255, 255));
        Crow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Crow.setText("C");
        Crow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Drow.setBackground(new java.awt.Color(255, 255, 255));
        Drow.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Drow.setForeground(new java.awt.Color(255, 255, 255));
        Drow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Drow.setText("D");
        Drow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/snickers.jpg"))); // NOI18N

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/snickers.jpg"))); // NOI18N

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/snickers.jpg"))); // NOI18N

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/snickers.jpg"))); // NOI18N

        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/hersheys.jpg"))); // NOI18N

        A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/hersheys.jpg"))); // NOI18N

        A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/hersheys.jpg"))); // NOI18N

        A8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/hersheys.jpg"))); // NOI18N

        col1.setBackground(new java.awt.Color(255, 255, 255));
        col1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        col1.setForeground(new java.awt.Color(255, 255, 255));
        col1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        col1.setText("1");
        col1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        col2.setBackground(new java.awt.Color(255, 255, 255));
        col2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        col2.setForeground(new java.awt.Color(255, 255, 255));
        col2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        col2.setText("2");
        col2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        col3.setBackground(new java.awt.Color(255, 255, 255));
        col3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        col3.setForeground(new java.awt.Color(255, 255, 255));
        col3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        col3.setText("3");
        col3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        col4.setBackground(new java.awt.Color(255, 255, 255));
        col4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        col4.setForeground(new java.awt.Color(255, 255, 255));
        col4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        col4.setText("4");
        col4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        col5.setBackground(new java.awt.Color(255, 255, 255));
        col5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        col5.setForeground(new java.awt.Color(255, 255, 255));
        col5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        col5.setText("5");
        col5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        col6.setBackground(new java.awt.Color(255, 255, 255));
        col6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        col6.setForeground(new java.awt.Color(255, 255, 255));
        col6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        col6.setText("6");
        col6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        col7.setBackground(new java.awt.Color(255, 255, 255));
        col7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        col7.setForeground(new java.awt.Color(255, 255, 255));
        col7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        col7.setText("7");
        col7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        col8.setBackground(new java.awt.Color(255, 255, 255));
        col8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        col8.setForeground(new java.awt.Color(255, 255, 255));
        col8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        col8.setText("8");
        col8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/Reeses.jpg"))); // NOI18N

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/Reeses.jpg"))); // NOI18N

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/Reeses.jpg"))); // NOI18N

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/Reeses.jpg"))); // NOI18N

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/hersheysA.jpg"))); // NOI18N

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/hersheysA.jpg"))); // NOI18N

        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/hersheysSD.jpg"))); // NOI18N

        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/hersheysSD.jpg"))); // NOI18N

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/nutrageous.jpg"))); // NOI18N

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/nutrageous.jpg"))); // NOI18N

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/nutrageous.jpg"))); // NOI18N

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/nutrageous.jpg"))); // NOI18N

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/babyruth.jpg"))); // NOI18N

        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/babyruth.jpg"))); // NOI18N

        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/babyruth.jpg"))); // NOI18N

        C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/babyruth.jpg"))); // NOI18N

        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/milkyway.jpg"))); // NOI18N

        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/milkyway.jpg"))); // NOI18N

        D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/milkyway.jpg"))); // NOI18N

        D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/milkyway.jpg"))); // NOI18N

        D5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/mnms.jpg"))); // NOI18N

        D6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/mnms.jpg"))); // NOI18N

        D7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/mnms.jpg"))); // NOI18N

        D8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/mnms.jpg"))); // NOI18N

        javax.swing.GroupLayout vendbgLayout = new javax.swing.GroupLayout(vendbg);
        vendbg.setLayout(vendbgLayout);
        vendbgLayout.setHorizontalGroup(
            vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendbgLayout.createSequentialGroup()
                .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(A2)
                            .addGroup(vendbgLayout.createSequentialGroup()
                                .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(A1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(col1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(col2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(col3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(col4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(col5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(col6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(col7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(col8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(666, 666, 666)
                        .addComponent(A6)
                        .addGap(127, 127, 127)
                        .addComponent(A8))
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Drow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addComponent(A5))
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(A4))
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(787, 787, 787)
                        .addComponent(A7))
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Crow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Arow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(vendbgLayout.createSequentialGroup()
                                .addComponent(Brow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(248, 248, 248)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(A3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        vendbgLayout.setVerticalGroup(
            vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendbgLayout.createSequentialGroup()
                .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(vendbgLayout.createSequentialGroup()
                            .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(vendbgLayout.createSequentialGroup()
                                    .addGap(127, 127, 127)
                                    .addComponent(Brow, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(vendbgLayout.createSequentialGroup()
                                    .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(vendbgLayout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(col1)
                                                .addComponent(col2)
                                                .addComponent(col3)
                                                .addComponent(col4)
                                                .addComponent(col5)
                                                .addComponent(col6)
                                                .addComponent(col7)
                                                .addComponent(col8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(A1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vendbgLayout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(A5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(A3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(A4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(A7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(A2, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(B1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(B2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(B3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(B4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(B5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(B6, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(B7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(B8, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(C1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C8, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(vendbgLayout.createSequentialGroup()
                            .addGap(209, 209, 209)
                            .addComponent(Crow, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vendbgLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Arow, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vendbgLayout.createSequentialGroup()
                                .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(A6)
                                    .addComponent(A8))
                                .addGap(170, 170, 170)
                                .addGroup(vendbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(D1)
                                    .addComponent(Drow, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D2)
                                    .addComponent(D3)
                                    .addComponent(D4)
                                    .addComponent(D5)
                                    .addComponent(D6)
                                    .addComponent(D7)
                                    .addComponent(D8))))))
                .addGap(43, 43, 43))
        );

        vendpanel.add(vendbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1060, 410));

        buttonA.setText("A");
        buttonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAActionPerformed(evt);
            }
        });
        vendpanel.add(buttonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 60, 40));

        buttonB.setText("B");
        buttonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBActionPerformed(evt);
            }
        });
        vendpanel.add(buttonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 60, 40));

        buttonC.setText("C");
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });
        vendpanel.add(buttonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 60, 40));

        buttonD.setText("D");
        buttonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDActionPerformed(evt);
            }
        });
        vendpanel.add(buttonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 60, 40));

        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        vendpanel.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 60, 40));

        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        vendpanel.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 60, 40));

        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        vendpanel.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 60, 40));

        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        vendpanel.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 60, 40));

        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        vendpanel.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 60, 40));

        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        vendpanel.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 60, 40));

        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        vendpanel.add(button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 60, 40));

        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        vendpanel.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 60, 40));

        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        vendpanel.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 60, 40));

        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        vendpanel.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 60, 40));

        buttonepay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonepay.setText("PAY");
        buttonepay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonepayActionPerformed(evt);
            }
        });
        vendpanel.add(buttonepay, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 120, 70));

        buttonclear.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonclear.setText("CLEAR");
        buttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonclearActionPerformed(evt);
            }
        });
        vendpanel.add(buttonclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 120, 70));

        buttoncheckout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttoncheckout.setText("CHECKOUT");
        buttoncheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncheckoutActionPerformed(evt);
            }
        });
        vendpanel.add(buttoncheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 120, 150));

        itemcodelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemcodelabel.setForeground(new java.awt.Color(255, 255, 255));
        itemcodelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcodelabel.setText("Item Code:");
        itemcodelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(itemcodelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 80, 30));

        amountlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountlabel.setForeground(new java.awt.Color(255, 255, 255));
        amountlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountlabel.setText("Amount:");
        amountlabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(amountlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 80, 30));

        pricelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pricelabel.setForeground(new java.awt.Color(255, 255, 255));
        pricelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pricelabel.setText("Price:");
        pricelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(pricelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 80, 30));

        priceval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceval.setForeground(new java.awt.Color(255, 255, 255));
        priceval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceval.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(priceval, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 220, 30));

        amountval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountval.setForeground(new java.awt.Color(255, 255, 255));
        amountval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountval.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(amountval, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 220, 30));

        itemcodeval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemcodeval.setForeground(new java.awt.Color(255, 255, 255));
        itemcodeval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcodeval.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(itemcodeval, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 220, 30));

        itemnamelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        itemnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemnamelabel.setText("Item Name:");
        itemnamelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(itemnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 80, 30));

        itemnameval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemnameval.setForeground(new java.awt.Color(255, 255, 255));
        itemnameval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemnameval.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(itemnameval, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 220, 30));

        cashlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashlabel.setForeground(new java.awt.Color(255, 255, 255));
        cashlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashlabel.setText("Cash");
        cashlabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(cashlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 80, 30));

        cashval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashval.setForeground(new java.awt.Color(255, 255, 255));
        cashval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashval.setText("$ 0.00");
        cashval.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(cashval, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 220, 30));

        changeval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeval.setForeground(new java.awt.Color(255, 255, 255));
        changeval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeval.setText("$ 0.00");
        changeval.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(changeval, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, 220, 30));

        changelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changelabel.setForeground(new java.awt.Color(255, 255, 255));
        changelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changelabel.setText("Change");
        changelabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendpanel.add(changelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 660, 80, 30));

        vendbgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codingchallenge/Assets/Wiki-background.jpg"))); // NOI18N
        vendpanel.add(vendbgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vendpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vendpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAActionPerformed
        Entervalue("A");   
    }//GEN-LAST:event_buttonAActionPerformed

    private void buttonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBActionPerformed
        Entervalue("B");
    }//GEN-LAST:event_buttonBActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        Entervalue("C");
    }//GEN-LAST:event_buttonCActionPerformed

    private void buttonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDActionPerformed
        Entervalue("D");
    }//GEN-LAST:event_buttonDActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        Entervalue("7");
        if(itemcodeval.getText().equals("A" + "7")){
            itemnameval.setText("Hershey's");
            priceval.setText("$" + hprice);  
            amountval.setText(Integer.toString(hamount));

        }       
        else if(itemcodeval.getText() == null ? "B" + "7" == null : itemcodeval.getText().equals("B" + "7")){
            itemnameval.setText("Hershey's Special Dark");
            priceval.setText("$" + hsdprice);  
            amountval.setText(Integer.toString(hsdamount));

        }
        else if(itemcodeval.getText() == null ? "C" + "7" == null : itemcodeval.getText().equals("C" + "7")){
            itemnameval.setText("Baby Ruth");
            priceval.setText("$" + brprice);  
            amountval.setText(Integer.toString(bramount));

        }
        else if(itemcodeval.getText() == null ? "D" + "7" == null : itemcodeval.getText().equals("D" + "7")){
            itemnameval.setText("M&M's");
            priceval.setText("$" + mmprice);  
            amountval.setText(Integer.toString(mmamount));

        }
        else{
        
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        }
           
        
    }//GEN-LAST:event_button7ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        Entervalue("4");
        if(itemcodeval.getText() == null ? "A" + "4" == null : itemcodeval.getText().equals("A" + "4")){
            itemnameval.setText("Snickers");
            priceval.setText("$" + sprice);  
            amountval.setText(Integer.toString(samount));
        }
        else if(itemcodeval.getText() == null ? "B" + "4" == null : itemcodeval.getText().equals("B" + "4")){
            itemnameval.setText("Reese's");
            priceval.setText("$" + rprice);  
            amountval.setText(Integer.toString(ramount));
        }
        else if(itemcodeval.getText() == null ? "C" + "4" == null : itemcodeval.getText().equals("C" + "4")){
            itemnameval.setText("Nutrageous");
            priceval.setText("$" + nrprice);  
            amountval.setText(Integer.toString(nramount));
        }
        else if(itemcodeval.getText() == null ? "D" + "4" == null : itemcodeval.getText().equals("D" + "4")){
            itemnameval.setText("MilkyWay");
            priceval.setText("$" + mwprice);  
            amountval.setText(Integer.toString(mwamount));
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        Entervalue("1");       
        if(itemcodeval.getText() == null ? "A" + "1" == null : itemcodeval.getText().equals("A" + "1")){
            itemnameval.setText("Snickers");
            priceval.setText("$" + sprice);  
            amountval.setText(Integer.toString(samount));
        }
        else if(itemcodeval.getText() == null ? "B" + "1" == null : itemcodeval.getText().equals("B" + "1")){
            itemnameval.setText("Reese's");
            priceval.setText("$" + rprice);  
            amountval.setText(Integer.toString(ramount));
        }
        else if(itemcodeval.getText() == null ? "C" + "1" == null : itemcodeval.getText().equals("C" + "1")){
            itemnameval.setText("Nutrageous");
            priceval.setText("$" + nrprice);  
            amountval.setText(Integer.toString(nramount));
        }
        else if(itemcodeval.getText() == null ? "D" + "1" == null : itemcodeval.getText().equals("D" + "1")){
            itemnameval.setText("MilkyWay");
            priceval.setText("$" + mwprice);  
            amountval.setText(Integer.toString(mwamount));
        }
        else{
        
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        Entervalue("8");        
        if(itemcodeval.getText() == null ? "A" + "8" == null : itemcodeval.getText().equals("A" + "8")){
            itemnameval.setText("Hershey's");
            priceval.setText("$" + hprice);  
            amountval.setText(Integer.toString(hamount));
        }
        else if(itemcodeval.getText() == null ? "B" + "8" == null : itemcodeval.getText().equals("B" + "8")){
            itemnameval.setText("Hershey's Special Dark");
            priceval.setText("$" + hsdprice);  
            amountval.setText(Integer.toString(hsdamount));
        }
        else if(itemcodeval.getText() == null ? "C" + "8" == null : itemcodeval.getText().equals("C" + "8")){
            itemnameval.setText("Baby Ruth");
            priceval.setText("$" + brprice);  
            amountval.setText(Integer.toString(bramount));
        }
        else if(itemcodeval.getText() == null ? "D" + "8" == null : itemcodeval.getText().equals("D" + "8")){
            itemnameval.setText("M&M's");
            priceval.setText("$" + mmprice);  
            amountval.setText(Integer.toString(mmamount));
        }
        else{
        
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        }
    }//GEN-LAST:event_button8ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        Entervalue("5");
        if(itemcodeval.getText() == null ? "A" + "5" == null : itemcodeval.getText().equals("A" + "5")){
            itemnameval.setText("Hershey's");
            priceval.setText("$" + hprice);  
            amountval.setText(Integer.toString(hamount));
        }
        else if(itemcodeval.getText() == null ? "B" + "5" == null : itemcodeval.getText().equals("B" + "5")){
            itemnameval.setText("Hershey's Almond");
            priceval.setText("$" + haprice);  
            amountval.setText(Integer.toString(haamount));
        }
        else if(itemcodeval.getText() == null ? "C" + "5" == null : itemcodeval.getText().equals("C" + "5")){
            itemnameval.setText("Baby Ruth");
            priceval.setText("$" + brprice);  
            amountval.setText(Integer.toString(bramount));
        }
        else if(itemcodeval.getText() == null ? "D" + "5" == null : itemcodeval.getText().equals("D" + "5")){
            itemnameval.setText("M&M's");
            priceval.setText("$" + mmprice);  
            amountval.setText(Integer.toString(mmamount));
        }
        else{
        
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        Entervalue("2");
        if(itemcodeval.getText() == null ? "A" + "2" == null : itemcodeval.getText().equals("A" + "2")){
            itemnameval.setText("Snickers");
            priceval.setText("$" + sprice);  
            amountval.setText(Integer.toString(samount));
        }
        else if(itemcodeval.getText() == null ? "B" + "2" == null : itemcodeval.getText().equals("B" + "2")){
            itemnameval.setText("Reese's");
            priceval.setText("$" + rprice);  
            amountval.setText(Integer.toString(ramount));
        }
        else if(itemcodeval.getText() == null ? "C" + "2" == null : itemcodeval.getText().equals("C" + "2")){
            itemnameval.setText("Nutrageous");
            priceval.setText("$" + nrprice);  
            amountval.setText(Integer.toString(nramount));
        }
        else if(itemcodeval.getText() == null ? "D" + "2" == null : itemcodeval.getText().equals("D" + "2")){
            itemnameval.setText("MilkyWay");
            priceval.setText("$" + mwprice);  
            amountval.setText(Integer.toString(mwamount));
        }
        else{
        
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        Entervalue("0");
        if(itemcodeval.getText() == null ? "A" + "0" == null : itemcodeval.getText().equals("A" + "0")){
            itemnameval.setText("No Item Found");
        }
        else if(itemcodeval.getText() == null ? "B" + "0" == null : itemcodeval.getText().equals("B" + "0")){
            itemnameval.setText("No Item Found");
        }
        else if(itemcodeval.getText() == null ? "C" + "0" == null : itemcodeval.getText().equals("C" + "0")){
            itemnameval.setText("No Item Found");
        }
        else if(itemcodeval.getText() == null ? "D" + "0" == null : itemcodeval.getText().equals("D" + "0")){
            itemnameval.setText("No Item Found");
        }
        else if(itemcodeval.getText().equals("A1B1C1D10")){
            new ServiceOption().setVisible(true);
            new ServiceOption().pack();
            new ServiceOption().setLocationRelativeTo(null);
            new ServiceOption().setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            dispose();
            
            System.out.println("Enter Machine Sevicing Option!");
            Date obj = new Date();        
            System.out.println(obj);
            System.out.println("======================================");
        }
        else{
        
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        }
    }//GEN-LAST:event_button0ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        Entervalue("9");
        if(itemcodeval.getText() == null ? "A" + "9" == null : itemcodeval.getText().equals("A" + "9")){
            itemnameval.setText("No Item Found");
        }
        else if(itemcodeval.getText() == null ? "B" + "9" == null : itemcodeval.getText().equals("B" + "9")){
            itemnameval.setText("No Item Found");
        }
        else if(itemcodeval.getText() == null ? "C" + "9" == null : itemcodeval.getText().equals("C" + "9")){
            itemnameval.setText("No Item Found");
        }
        else if(itemcodeval.getText() == null ? "D" + "9" == null : itemcodeval.getText().equals("D" + "9")){
            itemnameval.setText("No Item Found");
        }
        else{
        
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        }
    }//GEN-LAST:event_button9ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        Entervalue("6");
        if(itemcodeval.getText() == null ? "A" + "6" == null : itemcodeval.getText().equals("A" + "6")){
            itemnameval.setText("Hershey's");
            priceval.setText("$" + hprice);  
            amountval.setText(Integer.toString(hamount));
        }
        else if(itemcodeval.getText() == null ? "B" + "6" == null : itemcodeval.getText().equals("B" + "6")){
            itemnameval.setText("Hershey's Almond");
            priceval.setText("$" + haprice);  
            amountval.setText(Integer.toString(haamount));
        }
        else if(itemcodeval.getText() == null ? "C" + "6" == null : itemcodeval.getText().equals("C" + "6")){
            itemnameval.setText("Baby Ruth");
            priceval.setText("$" + brprice);  
            amountval.setText(Integer.toString(bramount));
        }
        else if(itemcodeval.getText() == null ? "D" + "6" == null : itemcodeval.getText().equals("D" + "6")){
            itemnameval.setText("M&M's");
            priceval.setText("$" + mmprice);  
            amountval.setText(Integer.toString(mmamount));
        }
        else{
        
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        Entervalue("3");
        if(itemcodeval.getText() == null ? "A" + "3" == null : itemcodeval.getText().equals("A" + "3")){
            itemnameval.setText("Snickers");
            priceval.setText("$" + sprice);  
            amountval.setText(Integer.toString(samount));
        }
        else if(itemcodeval.getText() == null ? "B" + "3" == null : itemcodeval.getText().equals("B" + "3")){
            itemnameval.setText("Reese's");
            priceval.setText("$" + rprice);  
            amountval.setText(Integer.toString(ramount));
        }
        else if(itemcodeval.getText() == null ? "C" + "3" == null : itemcodeval.getText().equals("C" + "3")){
            itemnameval.setText("Nutrageous");
            priceval.setText("$" + nrprice);  
            amountval.setText(Integer.toString(nramount));
        }
        else if(itemcodeval.getText() == null ? "D" + "3" == null : itemcodeval.getText().equals("D" + "3")){
            itemnameval.setText("MilkyWay");
            priceval.setText("$" + mwprice);  
            amountval.setText(Integer.toString(mwamount));
        }
        else{
        
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void buttonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonclearActionPerformed
        itemcodeval.setText("");
        itemnameval.setText("");
        amountval.setText("");
        priceval.setText("");
        cashval.setText("");
        changeval.setText("");
        buttoncheckout.setVisible(false);
        cashlabel.setVisible(false);
        cashval.setVisible(false);
        changelabel.setVisible(false);
        changeval.setVisible(false);
        
    }//GEN-LAST:event_buttonclearActionPerformed

    private void buttonepayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonepayActionPerformed
    
    
    String cash = JOptionPane.showInputDialog(this, "Enter Payment Amount","0");
      
    
    payments = Double.parseDouble(cash);
    
    
     if(payments == 0){
           JOptionPane.showMessageDialog(this, "Insufficient Balance");
           buttonepayActionPerformed(evt);
        }
     else if(itemnameval.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter selection!");
            buttoncheckout.setVisible(false);
        }       
     else{
        cashval.setText("$" + cash);
        cashlabel.setVisible(true);
        cashval.setVisible(true);
        buttoncheckout.setVisible(true);
    }
    
    }//GEN-LAST:event_buttonepayActionPerformed

    private void buttoncheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncheckoutActionPerformed
        if(itemnameval.getText().equals("Snickers")){
            remain = samount --;
            amountval.setText(Integer.toString(remain));
            balance = sprice;
            if(samount <= 0){
                amountval.setText("Out of Stock");
            }           
        }
        if(itemnameval.getText().equals("Hershey's")){
            remain = hamount --;
            amountval.setText(Integer.toString(remain));
            balance = hprice;
            if(hamount <= 0){
                amountval.setText("Out of Stock");
            }           
        }
        if(itemnameval.getText().equals("Hershey's Almond")){
            remain = haamount --;
            amountval.setText(Integer.toString(remain));
            balance = haprice;
            if(haamount <= 0){
                amountval.setText("Out of Stock");
            }           
        }
        if(itemnameval.getText().equals("Hershey's Special Dark")){
            remain = haamount --;
            amountval.setText(Integer.toString(remain));
            balance = hsdprice;
            if(haamount <= 0){
                amountval.setText("Out of Stock");
            }           
        }
        if(itemnameval.getText().equals("Reese's")){
            remain = ramount --;
            amountval.setText(Integer.toString(remain));
            balance = rprice;
            if(ramount <= 0){
                amountval.setText("Out of Stock");
            }           
        }
        if(itemnameval.getText().equals("Nutrageous")){
            remain = nramount --;
            amountval.setText(Integer.toString(remain));
            balance = nrprice;
            if(nramount <= 0){
                amountval.setText("Out of Stock");
            }           
        }
        if(itemnameval.getText().equals("Baby Ruth")){
            remain = bramount --;
            amountval.setText(Integer.toString(remain));
            balance = brprice;
            if(bramount <= 0){
                amountval.setText("Out of Stock");
            }           
        }
        if(itemnameval.getText().equals("MilkyWay")){
            remain = mwamount --;
            amountval.setText(Integer.toString(remain));
            balance = mwprice;
            if(mwamount <= 0){
                amountval.setText("Out of Stock");
            }           
        }
        if(itemnameval.getText().equals("M&M's")){
            remain = mmamount --;
            amountval.setText(Integer.toString(remain));
            balance = mmprice;
            if(mmamount <= 0){
                amountval.setText("Out of Stock");
            }           
        }
        
        else if(payments < balance){
         JOptionPane.showMessageDialog(this, "Insufficient Balance");
            buttonepayActionPerformed(evt);
        }
        
        changelabel.setVisible(true);
        changeval.setVisible(true);
        change = payments - balance;
        changeval.setText("$" + Double.toString(change));
                          
        Date obj = new Date();
        
        System.out.println(obj);
        System.out.println("Item Code  :" + itemcodeval.getText());
        System.out.println("Item Name  :" + itemnameval.getText());
        System.out.println("Current Amount  :" + amountval.getText());
        System.out.println("Item Price  :" + priceval.getText());
        System.out.println("Cash Inserted  :" + cashval.getText());
        System.out.println("Change  :" + changeval.getText());
        System.out.println("==========================================");
        
        buttoncheckout.setVisible(false);
        
        Receipt rcpt = new Receipt();
        rcpt.show();
        
        
              
    }//GEN-LAST:event_buttoncheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendingMachine().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel Arow;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JLabel Brow;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel Crow;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D3;
    private javax.swing.JLabel D4;
    private javax.swing.JLabel D5;
    private javax.swing.JLabel D6;
    private javax.swing.JLabel D7;
    private javax.swing.JLabel D8;
    private javax.swing.JLabel Drow;
    private javax.swing.JLabel amountlabel;
    public static javax.swing.JLabel amountval;
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonA;
    private javax.swing.JButton buttonB;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonD;
    public static javax.swing.JButton buttoncheckout;
    private javax.swing.JButton buttonclear;
    private javax.swing.JButton buttonepay;
    public static javax.swing.JLabel cashlabel;
    public static javax.swing.JLabel cashval;
    public static javax.swing.JLabel changelabel;
    public static javax.swing.JLabel changeval;
    private javax.swing.JLabel col1;
    private javax.swing.JLabel col2;
    private javax.swing.JLabel col3;
    private javax.swing.JLabel col4;
    private javax.swing.JLabel col5;
    private javax.swing.JLabel col6;
    private javax.swing.JLabel col7;
    private javax.swing.JLabel col8;
    private javax.swing.JLabel itemcodelabel;
    public static javax.swing.JLabel itemcodeval;
    private javax.swing.JLabel itemnamelabel;
    public static javax.swing.JLabel itemnameval;
    private javax.swing.JLabel pricelabel;
    public static javax.swing.JLabel priceval;
    private javax.swing.JPanel vendbg;
    private javax.swing.JLabel vendbgimg;
    private javax.swing.JPanel vendpanel;
    // End of variables declaration//GEN-END:variables
}
